name: Publish Docker image

on:
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    name: Push Docker image to Repositories
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: build images
        run: | 
          rake build
      - name: login to dockerhub
        run: podman login docker.io -u ${{ secrets.OOD_DOCKERHUB_USER }} -p ${{ secrets.OOD_DOCKERHUB_TOKEN }}
      - name: push images to dockerhub
        run: |
          rake publish['docker.io']
